services:
  embytoalist_t:
    image: 请自行构建，使用dockerfile
    env_file:
      - .env
    volumes:
      - /home/ubuntu/EmbyToAlist/cache:/app/cache
    user: 1000:1000
    network_mode: host

    restart: unless-stopped
