set $emby "http://127.0.0.1:8096"; 
    # reverse proxy
location ~* ^/preventRedirect/(emby/)?videos/(\d*)/(stream|original).* {
        rewrite ^/preventRedirect/(.*)$ /$1 break; 
        proxy_pass $emby; 
        #proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        #proxy_set_header Range $slice_range;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection ""; 
        add_header Strict-Transport-Security "max-age=31536000"; 
        proxy_http_version 1.1; 
        add_header Cache-Control no-cache; 
        proxy_cache off; 
    }
    # /emby/Videos/12345/xxx/Subtitles/3/0/Stream.ass?api_key=xx
location ~* /videos/(\d*)/(stream|original).* {
        proxy_cache off; 
        proxy_buffering off; 
        proxy_set_header Host $http_host; 
        proxy_set_header Range $http_range; 
        proxy_set_header If-Range $http_if_range; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_http_version 1.1; 
        proxy_set_header Connection ""; 
        proxy_pass http://127.0.0.1:60001; 
        #      add_header Referrer-Policy "no-referrer" always;
    }
    # Proxy sockets traffic for jellyfin-mpv-shim and webClient
location ~* /(socket|embywebsocket) {
        # Proxy emby/jellyfin Websockets traffic
        proxy_pass $emby; 
        ## WEBSOCKET SETTINGS ## Used to pass two way real time info to and from emby and the client.
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection $http_connection; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_set_header X-Forwarded-Protocol $scheme; 
        proxy_set_header X-Forwarded-Host $http_host; 
        proxy_connect_timeout 1h; 
        proxy_send_timeout 1h; 
        proxy_read_timeout 1h; 
        tcp_nodelay on; ## Sends data as fast as it can not buffering large chunks, saves about 200ms per request.
    }